# This is a basic workflow that is manually triggered

name: Build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - develop  # Trigger when code is pushed to develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm install
          npm run build  # Build the project

      - name: Deploy to Build Branch
        run: |
          git config --global user.name "szorawar2"
          git config --global user.email "zorawar355@gmail.com"
          git checkout -b build || git checkout build
          git rm -rf .  # Clean up old files
          cp -r build/* .  # Copy new build files
          git add .
          git commit -m "Deploy build from develop"
          git push --force origin build
