# This is a basic workflow that is manually triggered

name: Build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - develop # Trigger when code is pushed to develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: |
          git checkout develop
          npm run build
      - name: Deploy to Build Branch
        run: |
          git config --global user.name "szorawar2"
          git config --global user.email "zorawar355@gmail.com"
          git fetch origin  # Ensure remote branches are up-to-date
          git checkout -b build  # Create or switch to the build branch
          git rm -rf .  # Clean up old files
          cp -r dist/* .  # Copy new build files
          git add .
          git commit -m "Deploy build from develop"
          git push --force origin build
