# This is a basic workflow that is manually triggered

name: Clear build directory

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  clear:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Clear Build Branch
        run: |
          git config --global user.name "szorawar2"
          git config --global user.email "zorawar355@gmail.com"
          git fetch origin  # Ensure remote branches are up-to-date
          git checkout build  # Create or switch to the build branch
          git rm -rf .  # Clean up old files
          git add .
          git commit -m "Clear build branch"
          git push --force origin build
